<a href="https://colab.research.google.com/github/tomonari-masada/course2023-intro2ml/blob/main/04_NumPy_1_(in_class).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# モジュール、パッケージ、ライブラリ
https://docs.python.org/3/tutorial/modules.html
* "A module is a file containing Python definitions and statements."
* "Packages are a way of structuring Python’s module namespace by using “dotted module names”."

https://realpython.com/lessons/scripts-modules-packages-and-libraries/
* "A module is a Python file that’s intended to be imported into scripts or other modules."
* "A package is a collection of related modules that work together to provide certain functionality."
* "A library is an umbrella term that loosely means “a bundle of code.” These can have tens or even hundreds of individual modules that can provide a wide range of functionality."

## mathモジュール

In [ ]:
import math

a = 2.0
b = math.sqrt(a)
print(a, b)
b = math.exp(a)
print(a, b)

2.0 1.4142135623730951
2.0 7.38905609893065


## reモジュール
* 正規表現

In [ ]:
import re

s = 'one two one two'
m = re.finditer('one', s)
for match in m:
  print(match.start())

# NumPyライブラリ

* ベクトルや行列を扱える（他にも様々な機能がある）
 * ベクトルどうしの内積
 * 行列とベクトルの積
 * 行列と行列の積
 * 逆行列
 
* ndarrayという独自のデータ構造を使う
 * ちゃんとコードを書けば高速（ちゃんと書かないと遅い・・・）


## ndarray（NumPyの配列）の作り方

### Pythonのリストから作る

In [ ]:
import numpy as np

a = np.array([-2.3, 1.0, 3.0])
print(a)

[-2.3  1.   3. ]


In [ ]:
b = np.array([[1.0,2.0,3.0], [4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
print(b.T) #ndarrayの属性の例（転置属性）

[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [ ]:
aa = [1, 2, 3]
aa_new = []
for n in aa:
  aa_new.append(n * 3)
print(aa_new)


[3, 6, 9]


In [ ]:
a = np.array([1, 2, 3])
print(a * 3)
print(a + 2)

[3 6 9]
[3 4 5]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 0])
print(a + b)
#print(a / b) #警告が出る（どんな警告？）
print(a * b)
print(np.dot(a, b)) #内積

[3 4 3]
[2 4 0]
6


In [ ]:
a = np.array([-2.0, 1.0, 3.0])
b = np.array([[1,2,3], [4,5,6]])
print(a)
print(b)
print(np.dot(b, a))

[-2.  1.  3.]
[[1 2 3]
 [4 5 6]]
[ 9. 15.]


### ndarrayの属性

In [ ]:
a = np.array([-2.0, 1.0, 3.0])
b = np.array([[1,2,3], [4,5,6]])

#print(type(a)) #ndarray自体のデータ型
#print(a.data) #メモリ上での位置
#print(a.dtype) #要素のデータ型
#print(a.size, b.size)
#print(a.itemsize, b.itemsize) #要素のサイズ
#print(a.ndim, b.ndim) #次元数
print(a.shape, b.shape) #形状

(3,) (2, 3)


### ndarrayの作り方のいろいろ

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
b = np.arange(0, 10, 2)
print(b)

[0 2 4 6 8]


In [ ]:
x = np.linspace(0, 10, 101) #0以上10以下を10等分
print(x)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [ ]:
a = np.random.rand(3, 4) # 0~1の一様乱数
print(a)

[[0.5856319  0.25640604 0.75236514 0.68270169]
 [0.04384042 0.14104418 0.93387119 0.24286146]
 [0.08375371 0.01076977 0.06557479 0.61897676]]


In [ ]:
#print(np.random.randn()) #正規乱数

b = np.random.randn(3, 4)
print(b)
print(np.dot(a, b))
print(np.dot(b, a)) #エラー（なぜ？）

In [ ]:
a = np.ones((5, 4)) #()で囲む必要あり
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
b = np.ones((3, 5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
np.dot(a, b)

ValueError: ignored

In [ ]:

print(np.dot(b, b)) #なぜこうなる？

c = np.full((2,2), 7)
print(c)

## 配列の要素を指定する

### インデックス

In [ ]:
a = np.arange(1, 20, 3)
print(a)
print(a[0])
print(a[1])
a[3] = 11
print(a)
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c[0,0])
print(c[0,2])
print(c[1,2])

[ 1  4  7 10 13 16 19]
1
4
[ 1  4  7 11 13 16 19]
[[1 2 3]
 [4 5 6]]
1
3
6


In [ ]:
print(c)
c[1,1] = 50
print(c)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4 50  6]]


### 良くないコードの例

In [ ]:
import time
import numpy as np

x = np.ones(10000000)
y = np.ones(10000000)
s = np.zeros(10000000)
for _ in range(10):
  a = time.time()
  for i in range(10000000):
    s[i] = x[i] + y[i]
  b = time.time()
  print(b - a)

* 上のセルのように書くより、こう書くほうが良い

In [ ]:
import time
import numpy as np

x = np.ones(10000000)
y = np.ones(10000000)
s = np.zeros(10000000)
for _ in range(10):
  a = time.time()
  s = x + y
  b = time.time()
  print(b - a)

### スライシング

In [ ]:
a = np.arange(1, 20, 3)
print(a)

[ 1  4  7 10 13 16 19]


In [ ]:
print(a[4])

13


In [ ]:
print(a[1:4])

[ 4  7 10]


In [ ]:
print(a[0:6:2])

[ 1  7 13]


In [ ]:
print(a[::-1])

[19 16 13 10  7  4  1]


In [ ]:
print(a[3::-1])

[10  7  4  1]


In [ ]:
print(a)
print(a[-1:-4:-1])

[ 1  4  7 10 13 16 19]
[19 16 13]


In [ ]:
print(a[1:5])


print(a[-2::-1])
print(a[-2:1:-1])

### fancy index

In [ ]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)
m = a % 3 == 0
print(m)
print(type(m))
print(m.dtype)
b = a[m]
print(b) 

### where関数

In [ ]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)
m = np.where(a % 3 == 0) #インデックスのtupleを返す
print(m)
print(type(m))
b = a[m]
print(b) 

In [ ]:
np.random.seed(1234)
a = np.random.randint(10,size=10)
print(a)
m = np.where(a % 2 == 0, 'even', 'odd')
print(m)

print(a[m == 'even'])

## 配列のコピー

### 配列のビュー
* コピーではない

In [ ]:
a = np.array([1, 2, 3])
b = a #ビューを作っている
print(id(a) == id(b))

### 復習：リストのコピー

In [ ]:
a = [1, 2, 3]
b = a
b[1] = 22
print(a)
print(b)
c = a[:] #リストがコピーされる
c[2] = 234
print(a)
print(c)

## ndarrayの場合の`a[:]`

In [ ]:
a = np.array([1, 2, 3])
c = a[:] #コピーされるかどうか？
print(id(a) == id(c))
c[1] = 22
print(a) #変化している

### `copy`メソッド

In [ ]:
a = np.array([1, 2, 3])
d = a.copy() #コピーを作る
print(id(a) == id(d))
d[2] = 234
print(a) #変化していない

## in-place演算

In [ ]:
a = np.array([1, 2, 3])
c = a #ビューを作る
a = a + 1 #ここで別のオブジェクトになる
print(c)

a = np.array([1, 2, 3])
c = a #ビューを作る
a += 1 #in-place演算
print(c) #変化している

### in-place演算と演算関数の比較

In [ ]:
import time
import numpy as np

In [ ]:
size = 100000000
x = np.ones(size)
y = np.ones(size)
for _ in range(10):
  a = time.time()
  x = x * 4 + y * 3
  b = time.time()
  print(b - a)
  x = np.ones(size)
  y = np.ones(size)

In [ ]:
size = 100000000
x = np.ones(size)
y = np.ones(size)
for _ in range(10):
  a = time.time()
  x *= 4
  y *= 3
  x += y
  b = time.time()
  print(b - a)
  x = np.ones(size)
  y = np.ones(size)

In [ ]:
import time
import numpy as np

size = 100000000
x = np.ones(size)
y = np.ones(size)
for _ in range(10):
  a = time.time()
  np.multiply(x, 4, out=x)
  np.multiply(y, 3, out=y)
  np.add(x, y, out=x)
  b = time.time()
  print(b - a)
  x = np.ones(size)
  y = np.ones(size)

## 配列の形状を変更する

In [ ]:
a = np.arange(12)
print(a)
b = np.reshape(a, (3, 4)) #NumPyの関数reshape
print(b)
a[3] *= -1
print(a)
print(b) #変化している
c = a.reshape((2,6)) #ndarrayのreshapeメソッド
print(c)

[1. 1. 1. 1. 1. 1.]


In [ ]:
a = np.ones(6)
print(a)
b = a.copy()
print(b)
a[0] = 10 # bも変更される
print(a)
print(b)

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[10.  1.  1.  1.  1.  1.]
[1. 1. 1. 1. 1. 1.]


In [ ]:
a = [1,2,3,4,5]
print(a)
b = a # リストも代入文ではコピーされない
print(b)
a[0] = 10
print(a)
print(b)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[10, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


ごついデータは、代入文でコピーされない。

In [ ]:
x = 100.100
y = x
x = 1
print(x)
print(y)

1
100.1
